#spring:
#  datasource:
##    url: jdbc:mysql://localhost:3306/book_management?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://db:3306/book_management?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  output:
#    ansi:
#      enabled: ALWAYS
#
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#
#  application:
#    name: book-management-system
#    security:
#      jwt:
#        secretKey: ${JWT_SECRET}
#        EXPIRATION_TIME: ${EXPIRATION_TIME}
#
#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    locations: classpath:db/migration
#    validate-on-migrate: true
#    out-of-order: true
#
#logging:
#  level:
#    org.springframework: WARN
#    com.example.Book.Management: INFO
#
#server:
#  port: 8080


#####################  RENDER PLSQL  #####################

spring:
  datasource:
    # Render automatically injects the correct URL into SPRING_DATASOURCE_URL
    # Do not hardcode 'jdbc:mysql://...' here.
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  output:
    ansi:
      enabled: ALWAYS

  jpa:
    hibernate:
      # In production, this must be 'validate' or 'none'. Never 'update'.
      # Flyway handles the schema changes.
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  application:
    name: book-management-system
    security:
      jwt:
        secretKey: ${JWT_SECRET}
        EXPIRATION_TIME: ${EXPIRATION_TIME}

  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
    out-of-order: true

logging:
  level:
    # ERROR only for production to keep logs clean
    org.springframework: ERROR
    com.example.Book.Management: INFO

server:
  port: 8080
